### ISSUE TITLE
Password-Hash is saved in DB

### ISSUE THREAD

**Issue by karheinz** [ehsun7b/MyPasswords#13]
The Sha256-Hash of the password is saved in the database for later usage in the login dialog.

**Comment by ehsun7b** [comment]
Can you provide more details? issue? solution?

**Comment by karheinz** [comment]
LoginDialog.java

```
179     try {
180       Domain domain = Domain.getInstance();
181       String currentPassword = domain.getSetting("password", null);
182       currentPassword = currentPassword != null ? currentPassword : "";
183       String enteredPassword = new String(txtPassword.getPassword());
184       enteredPassword = Utils.SHA256(enteredPassword);
185 
186       if (currentPassword.equals(enteredPassword)) {
187         setVisible(false);
188         dispose();
189         loginResult = LOGIN_SUCCESSFULL;
190         domain.setPassword(new String(txtPassword.getPassword()));
191       } else {
192         JOptionPane.showMessageDialog(this, "Incorrect password!", "Warning", JOptionPane.WARNING_MESSAGE);
193         txtPassword.selectAll();
194         txtPassword.requestFocus();
```

Well, passwords have a low entropy (http://en.wikipedia.org/wiki/Entropy_%28information_theory%29). And calculating millions of hash values per second is no problem nowadays. As an attacker, i would start with a tool like John the ripper (http://www.openwall.com/john/doc/).

Better approach:
Use a well known key derivation algorithm like PBKDF2 and chose params carefully. KWallet for instance uses PBKDF2 with 50.000 iterations. To check the password you could derive the key and use it to calc a HMAC over some data. Then you compare it to a HMAC you calculated before (over the same data) and which is stored in the database.

**Comment by ehsun7b** [comment]
Same as previous issue u mentioned. this part has not been implemented yet. Thanks for ur time.
